server:
  port: 10003

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.200.131:3306/thyrodedb?useUnicode=true&serverTimezone=CST&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
      username: thyrodeUser
      password: thyrodeUser123!
      initial-size: 5
      max-active: 20
      min-idle: 1
      max-wait: 60000
      max-open-prepared-statements: 20
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat

      web-stat-filter:
        enabled: true
        url-pattern: /*
        profile-enable: true

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: curry
        login-password: 123456

  redis:
    host: 192.168.200.131
    port: 6379
    jedis:
      pool:
        min-idle: 2
        max-active: 10
        max-idle: 10

  jackson:
    default-property-inclusion: non_null

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://thyrode_discovery_local:local123@127.0.0.1:10002/eureka/